### ISSUE TITLE
(feature request) php5-cli

### ISSUE THREAD

**Issue by Pekinese** [geerlingguy/ansible-role-php#163]
First of all, great book @geerlingguy !

Maybe improve this role by adding an option to install php5-cli.
This is some kind of ugly on ubuntu16.04.
-Would be great, if you could include this!

**Comment by geerlingguy** [comment]
@Pekinese - Do you mean install PHP 5 (including CLI support) on Ubuntu 16.04? The defaults currently install CLI support in 7.0/7.1 on 16.04: https://github.com/geerlingguy/ansible-role-php/blob/master/vars/Debian.yml#L4

And for systems like Drupal VM, I found it easier if needing PHP 5.6 support to just use Ubuntu 14.04 instead of 16.04, or to compile PHP from source if I needed Ubuntu 16.04. See documentation here: http://docs.drupalvm.com/en/latest/other/php-56/
