### ISSUE TITLE
[Centos7] Some php packages from vars/RedHat.yml do not exist

### ISSUE THREAD

**Issue by pgporada** [geerlingguy/ansible-role-php#183]
Not working
```
TASK [geerlingguy.php : Ensure PHP packages are installed.] ********************
failed: [172.27.2.230] (item=[u'php', u'php-cli', u'php-common', u'php-devel', u'php-fpm', u'php-gd', u'php-ldap', u'php-mbstring', u'php-pdo', u'php-pear', u'php-pecl-apcu', u'php-xml', u'php-xmlrpc']) => {"changed": false, "failed": true, "item": ["php", "php-cli", "php-common", "php-devel", "php-fpm", "php-gd", "php-ldap", "php-mbstring", "php-pdo", "php-pear", "php-pecl-apcu", "php-xml", "php-xmlrpc"], "msg": "No package matching 'php-pecl-apcu' found available, installed or updated", "rc": 126, "results": ["No package matching 'php-pecl-apcu' found available, installed or updated"]}
```

Working
```
TASK [geerlingguy.php : Ensure PHP packages are installed.] ********************
changed: [172.27.2.230] => (item=[u'php', u'php-cli', u'php-common', u'php-devel', u'php-fpm', u'php-gd', u'php-ldap', u'php-mbstring', u'php-pdo', u'php-pear', u'php-xml', u'php-xmlrpc'])
```

I had to remove 
```
php-imap
php-opcache
php-pecl-apcu
```

My thought on this is to use an `- include_vars:` inside of the `vars/RedHat.yml` file when the system matches a specific `ansible_distribution_major_version`

**Comment by geerlingguy** [comment]
@pgporada - Interesting... the automated tests (see: https://travis-ci.org/geerlingguy/ansible-role-php) test on CentOS 7 and don't seem to have an issue installing those projects.

See how the test is run (an example playbook) here: https://github.com/geerlingguy/ansible-role-php/blob/master/tests/test.yml

Note that the tests (and pretty much _every_ usage I have for PHP on CentOS/RedHat) use the Remi repository to enable later (well-supported and modern) PHP versions. Otherwise you'll be stuck on 5.6 forever :)

But regardless, you can override the `php_packages` variable in your playbook (and should, since this role could someday change it's default list) and customize the list of php-related packages to install. My other projects (like Drupal VM) do this for stability and so I can have things set up just how I like them.
