### ISSUE TITLE
Undocumented variables

### ISSUE THREAD

**Issue by nkakouros** [geerlingguy/ansible-role-php#209]
There are some variables in tasks/main.yml such as php_extension_conf_paths and php_conf_paths that are not documented anywhere. If you feel these are too much to document for a simple user, how about creating an advanced section in the README?

**Comment by geerlingguy** [comment]
A lot of these variables are used when doing things like switching PHP versions on Debian (e.g. see https://github.com/geerlingguy/ansible-role-php-versions, used in Drupal VM), and as such would not be that helpful to document. However, if you or someone else would be able to put together a list of all the variables which can be overridden and aren't currently documented, I may be able to add something to the end of the Variables section in the README on them.

**Comment by tterranigma** [comment]
I will try to do that! 

The reason I opened this issue was the following.
I have installed php5.6 with php_packages, but the rest of the role configures basically php7. If someone wants to configure php5.6 they will need to change the conf_paths, in which case the lack of documentation makes it hard. 

This is what I have understood though and maybe I am wrong.

**Comment by nkakouros** [comment]
I don't have a use case for this anymore.
