### ISSUE TITLE
Debian default overwritten for session.savepath

### ISSUE THREAD

**Issue by ghost** [geerlingguy/ansible-role-php#218]
Now in php.ini.j2 there is a line

 `session.save_path = {{ php_session_save_path }}`

that makes PHP to use the path defined in the variable php_session_save_path for session files. In Debian this sessions.save_path is already predefined by a patch they have made: https://gitlab.com/deb.sury.org/php/raw/master-7.1/debian/patches/0018-session_save_path.patch (also similar patches are at least for Wheezy and Jessie versions). So at least for the people that use some Debian based distribution it would make sense to omit this line completely by using the conditionals provided by the templating system.

**Comment by kirjastojk** [comment]
What I use now is adding this variable to my plays:

`php_session_save_path: "{{ {'wheezy': '/var/lib/php5', 'jessie': '/var/lib/php5/sessions', 'stretch': '/var/lib/php/sessions'}[ansible_distribution_release] | default('') }}"`

so basically it checks if the distribution release name is any of those debian ones then it will but the value session.save_path accordingly. If the distribution release name is not any of those listed it will default to "" (/tmp). Having it like this adds up a bit more work to do because for each Debian release you need to add new key-value pair to the dictionary. Also to make this more robust one should also check whether the value in ansible_distribution is equal to "Debian" (because other distributions might have same release names).
