### ISSUE TITLE
version (3.7.0) of geerlingguy.php was not found in the list of available

### ISSUE THREAD

**Issue by mark-jones-entanet** [geerlingguy/ansible-role-php#283]
Today, in Packer, we've been getting the following error:

> amazon-ebs: [WARNING]: - geerlingguy.php was NOT installed successfully: - the specified

> amazon-ebs: version (3.7.0) of geerlingguy.php was not found in the list of available

Then it lists every other release of this package. Any idea whatt's wrong. We can't see any changes to the Pipeline.

**Comment by mark-jones-entanet** [comment]
It looks like it is an ansible galaxy issue as if you use a direct link to the repo here it works.

**Comment by cmcintosh** [comment]
seeing it to, worked last week.

**Comment by jonpugh** [comment]
Confirmed. This is definitely something with Galaxy API data: The latest version shown on https://galaxy.ansible.com/geerlingguy/php is 3.7.0, but if you let `ansible-galaxy` command decide what version, you get 3.6.3:

```
ansible-galaxy install geerlingguy.php
- downloading role 'php', owned by geerlingguy
- downloading role from https://github.com/geerlingguy/ansible-role-php/archive/3.6.3.tar.gz
- extracting geerlingguy.php to /home/jon/.ansible/roles/geerlingguy.php
- geerlingguy.php (3.6.3) was installed successfully
```

I only discovered it after attempting to use galaxy to install it. My travis runs for DevShop didn't catch it because it scaffolds up the source code with git first.

I am replicating DrupalVM methods to create @opendevshop containers using https://github.com/geerlingguy/drupal-vm/blob/master/provisioning/requirements.yml

I think this is worth raising with the @ansible/ansible-galaxy team.

**Comment by jonpugh** [comment]
Workaround is to modify your `requirements.yml` file:

```
- name: geerlingguy.php
  src: https://github.com/geerlingguy/ansible-role-php/archive/3.7.0.tar.gz
```

**Comment by geerlingguy** [comment]
See: https://github.com/ansible/galaxy/issues/2116#issuecomment-556137881

Basically, this was a bug in the `ansible-galaxy` client in Ansible 2.9.0. Upgrading to Ansible 2.9.1 should fix the issue.

It was causing build failures for every one of my php-related projects for a couple weeks... but now those are resolved, so I am much happier not seeing all those red X's :D
