### ISSUE TITLE
Backwards compatibility broken

### ISSUE THREAD

**Issue by tjoelsson** [geerlingguy/ansible-role-php#329]
The recently merged PR https://github.com/geerlingguy/ansible-role-php/pull/302 broke backwards compatibility. FPM configuration items for pool settings have been renamed. If you have these configured they no longer have any effect and default config will be used:

```yaml
php_fpm_listen
php_fpm_listen_allowed_clients
php_fpm_pm_max_children
php_fpm_pm_start_servers
php_fpm_pm_min_spare_servers
php_fpm_pm_max_spare_servers
```

**Comment by geerlingguy** [comment]
@rsicart had submitted that PR. Right now I don't have time to work on fixing this myself, but I would be willing to merge in a fix that preserves the backwards compatibility. Otherwise I'd also be willing to revert that PR since it's the last thing that was added and then we can look at getting something like it added again at some point in the future...

**Comment by rossmitchell** [comment]
Just hit this today. It also changes the pool location if you had configured it by setting the `php_fpm_pool_conf_path` to use a file other than www.conf

**Comment by geerlingguy** [comment]
Can you see if https://github.com/geerlingguy/ansible-role-php/pull/330 would fix?

**Comment by rossmitchell** [comment]
Not as it is at the moment. The destination is built using the conf path and the pool name here https://github.com/rsicart/ansible-role-php/blob/c62db9bbc1eb6864c257e17b0a6e9898926e48b9/tasks/configure-fpm.yml#L39

I think it could be fixed by adding a new property for the file name and defaulting it to `php_fpm_pool_conf_path | basename` and then using that when creating the pools

**Comment by geerlingguy** [comment]
@shakalandy - Could you see if you can get it to work that way instead?

**Comment by tjoelsson** [comment]
#330 Looks ok to me. It solves my issue.

**Comment by shakalandy** [comment]
will check that one tomorrow or later @geerlingguy @rossmitchell

**Comment by tjoelsson** [comment]
Any update? How about merging #330 first, then looking into additional problems in separate issues?

**Comment by geerlingguy** [comment]
Merged #330; we can solve any other issues as they crop up after.

**Comment by shakalandy** [comment]
@rossmitchell  could you please open a new ticket? I'll try to build a fix for that.

**Comment by rossmitchell** [comment]
@shakalandy I've created a new ticket for the pool name. I can take a look at it over the weekend and see if I can get a quick fix pushed up unless you want to look at it first

**Comment by tjoelsson** [comment]
Thank you!
