### ISSUE TITLE
Cross-platform module installation

### ISSUE THREAD

**Issue by sagikazarmark** [geerlingguy/ansible-role-php#52]
If I am correct, PHP module naming follows this pattern:

- Debian: php5-module
- RedHat: php-module

It would be nice if we could have a cross-platform option to install modules:

``` yml
php_modules:
    - cli
    - fpm
    - gd
```

**Comment by geerlingguy** [comment]
Unfortunately, if I switched to using this methodology, I would then have to branch out into _also_ having a platform-specific `php_packages` list, because while _most_ of the packages follow that convention, there are many that don't, like `php-pear` and `php-apc` on Debian.

Additionally, many common PHP repos and PPAs will use even more varied package naming conventions (e.g. `php7.0-[module]`), making any attempt at cross-platform package naming normalization a very frustrating experience :(

Because of this, I've elected to keep things simple and just have one `php_packages` list with the most common 'LAMP'-ish list I've seen, which can be overridden if necessary. As an example, here's a configuration for PHP 7 on Ubuntu 14.04: http://docs.drupalvm.com/en/latest/other/php-7/#ubuntu-1404
