### ISSUE TITLE
phpenmod/phpdismod on Ubuntu

### ISSUE THREAD

**Issue by thom8** [geerlingguy/ansible-role-php#93]
Currently this role creates static `.ini`'s for php modules for apache, fpm & cli, so modules can't be easily enabled and disabled with this helper script.

Would need to create the static common `.ini` files @ `/etc/php5/mods-available` and then symlink them to the `/conf.d` folders, `phpenmod` could be used to do the symlinking, depending on OS support.

example >>

```
php5dismod xdebug
WARNING: Module xdebug ini file doesn't exist under /etc/php5/mods-available
WARNING: Module xdebug ini file doesn't exist under /etc/php5/mods-available
WARNING: Module xdebug ini file doesn't exist under /etc/php5/mods-available
``` 

relates to https://github.com/geerlingguy/ansible-role-php-xdebug/issues/22

**Comment by geerlingguy** [comment]
Here's the thing... I detest a2enmod, php5dismod, et all—the whole idea of using strange platform/OS-specific shell script wrapper tools (which are version specific as well, meaning increased maintenance burden) irks me, because I'd rather manage all configuration via idempotent tools like Ansible.

On RedHat, Debian, etc. to disable an extension, you can just remove the config file, or comment out the `extension=` line, then restart the service.

I don't want to modify (and make even _more_ complex) the role config path layout just to make it better for some use cases on Debian/Ubuntu...

Sorry for the rant, but I just want to be clear that I am happy to do something to make enabling/disabling xdebug easier, but not at the expense of making things more complex, and definitely not in a way that's Debian/Ubuntu-specific.

**Comment by thom8** [comment]
Makes complete sense but at the same time not following the standards in place for the platform/OS could potentially lead to other issues + this actually might make it less complex for supporting multiple versions by having a single module `ini` file symlinked to the multiple locations.

**Comment by thom8** [comment]
Further to this and I'm not sure how it works on the RHEL, CentOS side of things but a common way to manage customisations to the `php.ini` file is with a custom ini in the `conf.d` dir.

This is often called `z_custom.ini` or similar so it's loaded last and can override defaults set in both the module and `php.ini`. Then you never need to modify the default files and wouldn't need to provide a full `php.ini` as a template.

There maybe be some good reasons not to do this but it could also help with managing multiple versions.

Happy to put some PR's together if it helps explain but wanted to discuss first.

**Comment by thom8** [comment]
phpenmod/phpdismod are not support on Ubuntu 12.04 as the default PHP version is 5.3 and this was introduced in 5.4.

**Comment by geerlingguy** [comment]
See also, an answer which I agree with: http://serverfault.com/a/56412/15673

> Debian/Ubuntu butcher the apache configuration into a large number of files, where directories of mods and sites enabled are symlinked to other snippets of configuration files. The a2enmod/a2ensite scripts just manipulate these symlinks.

It's really a philosophical difference, and I favor the RHEL approach (e.g. let your configuration management manage configuration... and don't twiddle with complicated symlink structures that are application-specific and not standard on _any_ other platform). My 2¢

**Comment by thom8** [comment]
I agree that it's possibly been over engineered which is why the helper scripts are even necessary. 
On the other hand this is different than the apache config as it allows for very specific control of each individual SAPI, and when working with a config management system should be abstracted anyway.

Would it not be easier to follow a platform standards (good or bad) rather than imposing another standard that conflicts with anything that assumes the platform standards are being used? 

It's not really philosophical when something doesn't work the way it's meant to.

**Comment by geerlingguy** [comment]
In this case, I would rather call it "using a standardized way of configuring a particular application's management across all platforms" rather than "not following a particular platform's standard"

In this particular case, it's a feature on a role that currently only officially supports Debian and RHEL. However, for other situations, like with Apache, I'm supporting Solaris, Fedora, and some other systems as well, and I just don't want to build a platform-specific way to manage all the bits of configuration... we'll have to agree to disagree, but the main thing for me is that I try as hard as I can to never log into a server (even for local dev), so supporting tools like `a2enmod` and `phpendmod` are non-starters for me.

**Comment by thom8** [comment]
It's actually not tools like `phpenmod` that are of primary concern, however it's a simple example. 

You'd probably find conflicts with most Debian server management applications which assume the platform standards are being used.

This is interesting as I've never had to deal with this kind of issue with in the past. I guess puppet/chef have mostly platform specific modules/recipes and therefore uses the platform standards which mitigates against these conflicts.

At the end of the day, it's good to know the project strategy as it may not work for my use case.

**Comment by geerlingguy** [comment]
> At the end of the day, it's good to know the project strategy as it may not work for my use case.

Definitely! And I want to be clear that I support primarily RHEL, but also support Debian because so many people use Ubuntu on desktop and then default to Debian for personal servers. So most of my tooling focuses as much as possible on RHEL, and also provides similar support for Debian.

There are many other roles on Galaxy which are Debian-specific, and Ansible itself sports the Apache2 module stuff natively: http://docs.ansible.com/ansible/apache2_module_module.html

I chose not to use that (nor a php module if one is added) just because it's _one more thing_ I have to track/test between platforms.
